    CREATE TABLE sweetpeppers (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        image TEXT NOT NULL
    );

    CREATE TABLE hotpeppers (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        image TEXT NOT NULL
    );

    CREATE TABLE crazypeppers (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        image TEXT NOT NULL
    );

    CREATE TABLE hybridpeppers (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        image TEXT NOT NULL
    );