CREATE TYPE categories AS enum (
    'hot',
    'crazy',
    'hybrid',
    'sweet'
);

CREATE TABLE peppers (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text NOT NULL,
    category categories NOT NULL,
    image text NOT NULL
);

